### ISSUE TITLE
Need a converter for converting YAML to TAML

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/oldTAML#12]

**Comment by cgleadall** [comment]
### How will the GitHub Action YAML file convert to TAML?
[github/Actions/dotnet-core.yml](https://github.com/csharpfritz/TAML/blob/main/.github/workflows/dotnet-core.yml)

**Lines 1 -7 are simple nested key values:**
```yaml
name: .NET Core

on:
  push:
    paths: src/dotnet/**
  pull_request:
    paths: src/dotnet/**
```
converts to?
```yaml
name    .NET Core

on
    push
        paths   src/dotnet/**
    pull_request
        paths   src/dotnet/**
```
---
**Lines 9-15 are simple nested key values:**
```yaml
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/dotnet
```
converts to?
```yaml
jobs
    build
        runs-on ubuntu-latest

    defaults
        run
            working-directory   src/dotnet
```
---
**Lines 17-28 are nested arrays?**
```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release
```
converts to?
```yaml
    steps
        uses    actions/checkout@v2
        name    Setup .NET Core
        uses    actions/setup-dotnet@v1
        with
            dotnet-version  3.1.301
        name    Install dependencies
        run dotnet restore
        name    build
        run dotnet build --configuration Release --no-restore
        name    Test
        run dotnet test --no-build --verbosity normal --configuration Release
  
```
---
**Lets focus on 1 of the action's steps at lines 19-22:**
```yaml
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
```
converts to?
```yml
        name    Setup .NET Core
        uses    actions/setup-dotnet@v1
        with
            dotnet-version  3.1.301
```
or
```yml
        name    Setup .NET Core
            uses    actions/setup-dotnet@v1
            with
                dotnet-version  3.1.301
```
Was I missing the extra indentation for the `uses` and `with`?
Are the `uses` and `with` "children" of the `name`?

Thanks
