### ISSUE TITLE
Deploy Python parser to Pip

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/oldTAML#36]
We should share the Python parser to Pip so that other developers can use it.

Should this just be a GitHub action?

**Comment by AlexHedley** [comment]
Untested, just getting some info together:

- [ ] Create an account [pypi](https://pypi.org/project/pip/) to distribute to on
- [ ] Add a `pypi_password` to the project settings
- [ ] Create a new workflow `publish-py.yml` in `.github/workflows/`

---

GitHub Action: [PyPI publish GitHub Action](https://github.com/pypa/gh-action-pypi-publish)

Get code
```
steps:
    - uses: actions/checkout@v2
```

Configure python version
```
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
```

Any dependencies?
```
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
```

Run tests?
```
    - name: Test with pytest
      run: |
        pytest
```

Build for distribution?
```
    - name: Build
      run: >-
        python setup.py sdist bdist_wheel
```
Update path to `src\python\setup.py`?

Publish
```
- name: Publish package
  # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  uses: pypa/gh-action-pypi-publish@master
  with:
    user: __token__
    password: ${{ secrets.pypi_password }}
```
