### ISSUE TITLE
Deploy .NET parser to NuGet

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/oldTAML#38]
Configure a GitHub action to deploy to NuGet

**Comment by BitCashCF** [comment]
Some of us aren't to familiar which end to switch, and turn roundabout, how dept became the knight crawler.

**Comment by AlexHedley** [comment]
Modify the following:

`.github/workflows/publish-nuget.yml`

Add a secret in the repo settings called `NUGET_API_KEY` and copy in your new API key ([Publishing Packages](https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package))

Update the `PROJECT_FILE_PATH`
Specify which branch.

```yml
name: Publish to NuGet

on:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'parsers/dotnet/**'

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
         uses: actions/checkout@v2
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      
      - name: Publish
        uses: rohith/publish-nuget@v2
        #uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: parsers/dotnet/Taml.NET/Taml.NET.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
```
